name: Build and Release Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (ej: v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Build with PyInstaller
      run: |
<<<<<<< HEAD
        pyinstaller --onefile --windowed --add-data "click.wav:." mision_numerologica_gui.py
=======
        pyinstaller --onefile --windowed --add-data "click.wav:." mission_numerologica_gui.py
>>>>>>> refs/remotes/origin/main
      shell: bash
    - name: Rename executable
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
<<<<<<< HEAD
          mv dist/mision_numerologica_gui.exe dist/NumerologiaGUI-windows.exe
        else
          mv dist/mision_numerologica_gui dist/NumerologiaGUI-linux
=======
          mv dist/mission_numerologica_gui.exe dist/NumerologiaGUI-windows.exe
        else
          mv dist/mission_numerologica_gui dist/NumerologiaGUI-linux
>>>>>>> refs/remotes/origin/main
        fi
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: numerologia-${{ matrix.os }}
        path: dist/NumerologiaGUI-*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - name: Create Release and upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        files: artifacts/*
